<a href="https://colab.research.google.com/github/najminfy/p/blob/main/4111422049_Najmi_Fachrudin_Y_UTS_Datmin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

#membaca file data training dan menampilkan informasi umum
data_train=pd.read_csv('data_training.csv')
print(data_train.info())

#membaca file data testing dan menampilkan informasi umum
data_test=pd.read_csv('data_testing.csv')
print(data_test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 857 entries, 0 to 856
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         857 non-null    float64
 1   volatile acidity      857 non-null    float64
 2   citric acid           857 non-null    float64
 3   residual sugar        857 non-null    float64
 4   chlorides             857 non-null    float64
 5   free sulfur dioxide   857 non-null    float64
 6   total sulfur dioxide  857 non-null    float64
 7   density               857 non-null    float64
 8   pH                    857 non-null    float64
 9   sulphates             857 non-null    float64
 10  alcohol               857 non-null    float64
 11  quality               857 non-null    int64  
 12  Id                    857 non-null    int64  
dtypes: float64(11), int64(2)
memory usage: 87.2 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
D

In [2]:
data_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0              7.3             0.740         0.08             1.7      0.094   
1              8.1             0.575         0.22             2.1      0.077   
2             10.1             0.430         0.40             2.6      0.092   
3             12.9             0.500         0.55             2.8      0.072   
4              8.4             0.360         0.32             2.2      0.081   
..             ...               ...          ...             ...        ...   
852            6.7             1.040         0.08             2.3      0.067   
853            8.0             0.390         0.30             1.9      0.074   
854            7.4             0.350         0.33             2.4      0.068   
855            7.9             0.570         0.31             2.0      0.079   
856            7.5             0.520         0.40             2.2      0.060   

     free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                   10.0                  45.0  0.99576  3.24       0.50   
1                   12.0                  65.0  0.99670  3.29       0.51   
2                   13.0                  52.0  0.99834  3.22       0.64   
3                    7.0                  24.0  1.00012  3.09       0.68   
4                   32.0                  79.0  0.99640  3.30       0.72   
..                   ...                   ...      ...   ...        ...   
852                 19.0                  32.0  0.99648  3.52       0.57   
853                 32.0                  84.0  0.99717  3.39       0.61   
854                  9.0                  26.0  0.99470  3.36       0.60   
855                 10.0                  79.0  0.99677  3.29       0.69   
856                 12.0                  20.0  0.99474  3.26       0.64   

     alcohol  quality    Id  
0        9.8        5  1366  
1        9.2        5   103  
2       10.0        7   942  
3       10.9        6   811  
4       11.0        6   918  
..       ...      ...   ...  
852     11.0        4  1467  
853      9.0        5  1533  
854     11.9        6  1580  
855      9.5        6  1216  
856     11.8        6  1575  

[857 rows x 13 columns]

In [3]:
#membagi data menjadi variabel x dan y
x=data_train.drop(['quality','Id'],axis=1)
y=data_train['quality']

In [4]:
#menormalisasikan data menjadi rentang 0-1 agar seimbang saat pelatihan model
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x=pd.DataFrame(scaler.fit_transform(x),columns=x.columns)
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0         0.245455          0.424658         0.08        0.054795   0.136895   
1         0.318182          0.311644         0.22        0.082192   0.108514   
2         0.500000          0.212329         0.40        0.116438   0.133556   
3         0.754545          0.260274         0.55        0.130137   0.100167   
4         0.345455          0.164384         0.32        0.089041   0.115192   
..             ...               ...          ...             ...        ...   
852       0.190909          0.630137         0.08        0.095890   0.091820   
853       0.309091          0.184932         0.30        0.068493   0.103506   
854       0.254545          0.157534         0.33        0.102740   0.093489   
855       0.300000          0.308219         0.31        0.075342   0.111853   
856       0.263636          0.273973         0.40        0.089041   0.080134   

     free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0               0.134328              0.143382  0.433359  0.393701   0.068323   
1               0.164179              0.216912  0.504950  0.433071   0.074534   
2               0.179104              0.169118  0.629855  0.377953   0.155280   
3               0.089552              0.066176  0.765423  0.275591   0.180124   
4               0.462687              0.268382  0.482102  0.440945   0.204969   
..                   ...                   ...       ...       ...        ...   
852             0.268657              0.095588  0.488195  0.614173   0.111801   
853             0.462687              0.286765  0.540746  0.511811   0.136646   
854             0.119403              0.073529  0.352628  0.488189   0.130435   
855             0.134328              0.268382  0.510282  0.433071   0.186335   
856             0.164179              0.051471  0.355674  0.409449   0.155280   

      alcohol  
0    0.250000  
1    0.142857  
2    0.285714  
3    0.446429  
4    0.464286  
..        ...  
852  0.464286  
853  0.107143  
854  0.625000  
855  0.196429  
856  0.607143  

[857 rows x 11 columns]

In [5]:
#membagi data training menjadi data train dan test untuk membuat dan melatih model prediksi
#20% data digunakan untuk membuat model prediksi dan 80% digunakan untuk menguji seberapa akurat modelnya
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [6]:
#membuat model prediksi dari x dan y data train dengan metode decision tree
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [7]:
#memprediksi nilai x test
#digunakan untuk membandingkan dengan y test
y_pred=classifier.predict(x_test)

In [8]:
#evaluasi model prediksi
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 0  0  2  0  0  0]
 [ 0  0  5  0  1  0]
 [ 1  0 52 23  3  1]
 [ 0  0 20 38  9  1]
 [ 0  0  0  9  6  0]
 [ 0  0  0  1  0  0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         6
           5       0.66      0.65      0.65        80
           6       0.54      0.56      0.55        68
           7       0.32      0.40      0.35        15
           8       0.00      0.00      0.00         1

    accuracy                           0.56       172
   macro avg       0.25      0.27      0.26       172
weighted avg       0.55      0.56      0.55       172



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [9]:
data_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0              6.8             0.610         0.04             1.5      0.057   
1              6.9             0.840         0.21             4.1      0.074   
2              7.0             0.580         0.12             1.9      0.091   
3              7.8             0.480         0.68             1.7      0.415   
4             12.5             0.600         0.49             4.3      0.100   
..             ...               ...          ...             ...        ...   
281           10.0             0.410         0.45             6.2      0.071   
282           10.6             0.830         0.37             2.6      0.086   
283            7.9             0.885         0.03             1.8      0.058   
284            7.3             0.670         0.02             2.2      0.072   
285           10.2             0.440         0.58             4.1      0.092   

     free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    5.0                  10.0  0.99525  3.42       0.60   
1                   16.0                  65.0  0.99842  3.53       0.72   
2                   34.0                 124.0  0.99560  3.44       0.48   
3                   14.0                  32.0  0.99656  3.09       1.06   
4                    5.0                  14.0  1.00100  3.25       0.74   
..                   ...                   ...      ...   ...        ...   
281                  6.0                  14.0  0.99702  3.21       0.49   
282                 26.0                  70.0  0.99810  3.16       0.52   
283                  4.0                   8.0  0.99720  3.36       0.33   
284                 31.0                  92.0  0.99566  3.32       0.68   
285                 11.0                  24.0  0.99745  3.29       0.99   

       alcohol    Id  
0     9.500000   222  
1     9.233333  1514  
2    10.500000   417  
3     9.100000   754  
4    11.900000   516  
..         ...   ...  
281  11.800000  1147  
282   9.900000   296  
283   9.100000   170  
284  11.066667  1439  
285  12.000000   946  

[286 rows x 12 columns]

In [10]:
#mendefinisikan variabel x pada file data testing
x_testing=data_test.drop('Id',axis=1)
x_testing=pd.DataFrame(scaler.fit_transform(x_testing),columns=x_testing.columns)
x_testing

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0         0.165138          0.373913     0.052632        0.021127   0.060367   
1         0.174312          0.573913     0.276316        0.204225   0.104987   
2         0.183486          0.347826     0.157895        0.049296   0.149606   
3         0.256881          0.260870     0.894737        0.035211   1.000000   
4         0.688073          0.365217     0.644737        0.218310   0.173228   
..             ...               ...          ...             ...        ...   
281       0.458716          0.200000     0.592105        0.352113   0.097113   
282       0.513761          0.565217     0.486842        0.098592   0.136483   
283       0.266055          0.613043     0.039474        0.042254   0.062992   
284       0.211009          0.426087     0.026316        0.070423   0.099738   
285       0.477064          0.226087     0.763158        0.204225   0.152231   

     free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0               0.030769              0.010638  0.343191  0.486957   0.166667   
1               0.200000              0.205674  0.589883  0.582609   0.240741   
2               0.476923              0.414894  0.370428  0.504348   0.092593   
3               0.169231              0.088652  0.445136  0.200000   0.450617   
4               0.030769              0.024823  0.790661  0.339130   0.253086   
..                   ...                   ...       ...       ...        ...   
281             0.046154              0.024823  0.480934  0.304348   0.098765   
282             0.353846              0.223404  0.564981  0.260870   0.117284   
283             0.015385              0.003546  0.494942  0.434783   0.000000   
284             0.430769              0.301418  0.375097  0.400000   0.216049   
285             0.123077              0.060284  0.514397  0.373913   0.407407   

      alcohol  
0    0.169231  
1    0.128205  
2    0.323077  
3    0.107692  
4    0.538462  
..        ...  
281  0.523077  
282  0.230769  
283  0.107692  
284  0.410256  
285  0.553846  

[286 rows x 11 columns]

In [11]:
#menggunakan model prediksi pada file data testing
y_predict=classifier.predict(x_testing)

In [12]:
#membuat dataset baru yang berisi ID dan hasil prediksi Quality
df=pd.DataFrame({'Id': data_test['Id'], 'Quality': y_predict})
df.head()

Id  Quality
0   222        4
1  1514        6
2   417        5
3   754        5
4   516        5

In [14]:
#import dataset menjadi file csv
from google.colab import files
df.to_csv("hasilprediksi_049.csv", index=False)
files.download("hasilprediksi_049.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Walaupun data sudah dinormalisasikan, akurasi model prediksi masih tidak begitu akurat. Hal ini ditunjukkan pada hasil confussion matrix bahwa hasil akurasi hanya berkisar pada 50-60%.